// packages/react/lib/base/MProgress.tsx
/**
 * @description react version progress
 * @author 阿怪
 * @date 2023/03/09 16:30
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/progress/progress.css';
import { ProgressProps } from '@shuimo-design/core/lib/base/progress';
import { Slot } from '../../types';
import { getProgressInfo, getProgressWrapperStyle, leaf } from '@shuimo-design/core/lib/base/progress/useProgress';
import { props as progressProps } from '@shuimo-design/core/lib/base/progress/api';
import { withDefault } from '../../base/tools';



export default function MProgress(baseProps: ProgressProps & Slot) {
  const props = withDefault(baseProps, progressProps);
  // todo use effect?
  const progressInfo = getProgressInfo(props);
  // @ts-ignore
  const progress = <progress className="m-progress" value={props.value} max={props.max} style={progressInfo.style}/>;
  if (!props.showInfo) {
    return progress;
  }


  const progressWrapperInfo = getProgressWrapperStyle(props, progressInfo);
  // @ts-ignore
  return <div className="m-progress-border" style={progressWrapperInfo.baseStyle}>
    <div className="m-progress-per" style={progressWrapperInfo.textStyle}>
      <img className="m-progress-leaf" src={leaf} alt=""/>
      {props.children}
    </div>
    {progress}
  </div>;
}

// lib/components/base/progress/MProgress.tsx
/**
 * @description 进度条组件
 * @author 阿怪
 * @date 2022/1/21 6:13 下午
 * @version v1.0.3
 *
 * 公司的业务千篇一律，复杂的代码好几百行。
 * v1.0.1 修复width与预期不一致的问题，优化渲染逻辑
 * v1.0.2 修复绝对定位造成竹叶及数字渲染位置错误的问题
 * v1.0.3 百分比模块改为slot模式（为支持nuxt ssr ）
 */
import { computed, defineComponent } from 'vue';
import { leaf, useProgress } from './useProgress.ts';
import { props } from './api.ts';
import './progress.css';

export default defineComponent((props, { slots }) => {
  const { getProgressWrapperStyle, getProgressInfo } = useProgress({ props });
  const progressInfo = computed(() => getProgressInfo());
  const progressWrapperInfo = computed(() => {
    if (props.showInfo) {
      return getProgressWrapperStyle(progressInfo.value);
    }
    return undefined
  });


  return () => {

    const progress = <progress class="m-progress"
                               value={props.value} max={props.max} style={progressInfo.value.style}/>;
    if (!props.showInfo) {
      return progress;
    }


    return <div class="m-progress-border" style={progressWrapperInfo.value?.baseStyle}>
      <div class="m-progress-per" style={progressWrapperInfo.value?.textStyle}>
        <img class="m-progress-leaf" src={leaf} alt=""/>
        {slots.default?.()}
      </div>
      {progress}
    </div>;
  };
}, {
  name: 'MProgress',
  props
});
