// packages/react/lib/base/MSwitch.tsx
/**
 * @description react version MSwitch
 * @author 阿怪
 * @date 2023/2/18 22:07
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 * todo click event
 */
import React from 'react';
import { useState } from 'react';
import { SwitchEvents, SwitchProps } from '@shuimo-design/core/lib/base/switch';
import { isEmpty } from '@shuimo-design/tools/empty';
import { Slot } from '../../types';
import '@shuimo-design/core/lib/style/global.css';
import '@shuimo-design/core/lib/base/switch/switch.css';


export default function MSwitch(props: SwitchProps & SwitchEvents & Slot) {

  let baseActiveValue = props.activeValue;
  let baseInactiveValue = props.inactiveValue;

  const isBoolean = typeof props.value === 'boolean';

  if (isBoolean) {
    // 如果activeValue和inactiveValue都为空
    if (isEmpty(props.activeValue) && isEmpty(props.inactiveValue)) {
      baseActiveValue = true;
      baseInactiveValue = false;
    }
  }

  const [activeValue, setActiveValue] = useState(baseActiveValue);
  const [inactiveValue, setInactiveValue] = useState(baseInactiveValue);

  const isActive = props.value === activeValue;

  const changeSwitch = () => {

  }

  const getInfo = (key: keyof Pick<SwitchProps, 'activeInfo' | 'inactiveInfo'>) => {
    // if (props.children[key]) {
    //   return slots[key]!();
    // }
    // return <span class="m-switch-span">{props[key]}</span>;
    return <span className="m-switch-span">{props[key]}</span>;
  };

  return <div className={[
    'm-switch',
    isActive ? 'm-switch-active' : 'm-switch-inactive',
    props.loading ? 'm-switch-loading' : '',
    props.disabled ? 'm-switch-disabled' : ''
  ].join(' ')}>
    {getInfo('activeInfo')}
    <div className="m-switch-main">
      <div className="m-switch-core" onClick={changeSwitch}>
        <div className="m-switch-core-border"></div>
      </div>
    </div>
    {getInfo('inactiveInfo')}
  </div>
}

// lib/components/base/switch/MSwitch.tsx
/**
 * @description 开关组件
 * @author 阿怪
 * @date 2022/8/16 23:07
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * modelValue不为布尔值的时候暂时不冒泡，里面的逻辑不太清晰，后续可以扩展一下
 */
import { computed, defineComponent, ref } from 'vue';
import { SwitchCore } from '@shuimo-design/ui-core/components/base/switch';
import { isEmpty } from '../../../tools';
import { SwitchProps } from '@shuimo-design/ui-core/components/base/switch/props';
import './switch.css';

export default defineComponent((props: SwitchProps, { emit, slots }) => {
  const activeValue = ref(props.activeValue);
  const inactiveValue = ref(props.inactiveValue);

  const isBoolean = computed(() => SwitchCore.switchIsBoolean(props.modelValue));

  // 如果modelValue是布尔值
  if (isBoolean.value) {
    // 如果activeValue和inactiveValue都为空
    if (isEmpty(props.activeValue) && isEmpty(props.inactiveValue)) {
      activeValue.value = true;
      inactiveValue.value = false;
    }
  }

  const isActive = computed(() => SwitchCore.getIsActive(props.modelValue, activeValue.value));

  const changeSwitch = () => {
    if (props.disabled || props.loading) {
      return;
    }
    // 如果不是自定义控制的
    if (!props.onControl) {
      // 如果是简单的布尔值
      if (isBoolean.value) {
        emit('update:modelValue', !props.modelValue);
      }
    }
    emit('change', !isActive.value ? props.activeValue ?? true : props.inactiveValue ?? false);
  };

  return () => {

    const getInfo = (key: keyof Pick<SwitchProps, 'activeInfo' | 'inactiveInfo'>) => {
      if (slots[key]) {
        return slots[key]!();
      }
      return <span class="m-switch-span">{props[key]}</span>;
    };


    return <div class={[
      'm-switch',
      isActive.value ? 'm-switch-active' : 'm-switch-inactive',
      { 'm-switch-loading': props.loading },
      { 'm-switch-disabled': props.disabled },
    ]}>
      {getInfo('activeInfo')}
      <div class="m-switch-main">
        <div class="m-switch-core" onClick={changeSwitch}>
          <div class="m-switch-core-border"></div>
        </div>
      </div>
      {getInfo('inactiveInfo')}
    </div>;
  };

}, {
  name: 'MSwitch',
  emits: ['update:modelValue', 'change'],
  props: SwitchCore.props,
});
