// packages/lit/lib/other/MDarkMode.ts
/**
 * @description web-component DarkMode template
 * @author 阿怪
 * @date 2023/1/31 11:25
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */

import { html, svg, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { DarkModeProps } from '@shuimo-design/core/lib/other/darkMode';
import style from '@shuimo-design/core/lib/other/darkMode/darkMode.css?inline';
import { useDarkMode } from '@shuimo-design/core/lib/other/darkMode/useDarkMode';

const { onMountedHook, toggleDarkMode } = useDarkMode();

@createMElement({
  name: 'dark-mode'
})
export default class MDarkMode extends LitElement implements DarkModeProps {
  public value: boolean = false;
  static styles = unsafeCSS(style);

  constructor() {
    super();
    const isDark = onMountedHook();
    if (isDark) {
      this.value = true;
      toggleDarkMode(this);
    }
  }

  clickHandler() {
    this.value = !this.value;
    toggleDarkMode(this);
  }

  get svg() {
    return svg`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 520" class="m-dark-mode-svg"
     stroke-width="1">
  <title>Dark Mode</title>
  <filter id="outset-shadow" x="-50%" y="-50%" width="200%" height="200%">
    <feDropShadow dx="0" dy="0" stdDeviation="20" flood-color="black"/>
  </filter>
  <filter id="outset-shadow-white" x="-50%" y="-50%" width="200%" height="200%">
    <feDropShadow dx="0" dy="0" stdDeviation="20" flood-color="white"/>
  </filter>
  <path
    class="svg-black"
    transform="translate(0)"
    fill="#000000"/>
  <path
    class="svg-white"
    transform="translate(0) rotate(180, 250, 250)"
    fill="#FFFFFF"/>
  <path
    class="fins"
    transform="translate(0)"
    fill="#000000"/>
  <circle class="svg-black" cx="250" cy="375" r="40"/>
  <circle class="svg-white" cx="250" cy="125" r="40" fill="#fff"/>
</svg>`;
  }

  render() {
    return html`
      <div class="m-dark-mode"
           @click=${(e: MouseEvent) => this.clickHandler()}>
        ${this.svg}
      </div>`;
  }

}

// packages/react/lib/other/MDarkMode.tsx
/**
 * @description react version MDarkMode
 * @author 阿怪
 * @date 2023/4/25 19:12
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { useState } from 'react';
import { DarkModeProps } from '@shuimo-design/core/lib/other/darkMode';
import { useDarkMode } from '@shuimo-design/core/lib/other/darkMode/useDarkMode';
import '@shuimo-design/core/lib/other/darkMode/darkMode.css';

export default function MDarkMode(props: DarkModeProps) {
  const { onMountedHook, toggleDarkMode } = useDarkMode();

  let isDarkMode = props.value;
  const clickHandler = () => {
    isDarkMode = !isDarkMode;
    toggleDarkMode({ value: !isDarkMode });
  };

  onMountedHook();

  const svg = <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 520" className="m-dark-mode-svg"
                   strokeWidth="1">
    <title>Dark Mode</title>
    <filter id="outset-shadow" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="20" floodColor="black"/>
    </filter>
    <filter id="outset-shadow-white" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="20" floodColor="white"/>
    </filter>
    <path
      className="svg-black"
      transform="translate(0)"
      fill="#000000"/>
    <path
      className="svg-white"
      transform="translate(0) rotate(180, 250, 250)"
      fill="#FFFFFF"/>
    <path
      className="fins"
      transform="translate(0)"
      fill="#000000"/>
    <circle className="svg-black" cx="250" cy="375" r="40"/>
    <circle className="svg-white" cx="250" cy="125" r="40" fill="#fff"/>
  </svg>;


  return <div className="m-dark-mode"
              onClick={() => clickHandler()}>
    {svg}
  </div>;

}
