// packages/vue/lib/message/popover/MPopover.tsx
/**
 * @description MPopover
 * @author youus
 * @date 2022/4/3 18:07
 * @version v2.0.0-process
 *
 * Hello, humor
 * v2.0.0-process 阿怪 准备重构，搭建模版
 */

import { defineComponent, ref } from 'vue';
import { usePopover } from '@shuimo-design/core';
import { cr } from '../../../tools/coreRender';

export default defineComponent({
  name: 'MPopover',
  // props:,
  emits: ['open:popper', 'close:popper', 'update:show'],
  setup(props, { slots, emit }) {
    const { getTemplate } = usePopover();

    const popoverRef = ref<HTMLElement>();
    const contentRef = ref<HTMLElement>();

    return () => {
      return cr(getTemplate({
        ref: { popoverRef, contentRef },
      }), { slots });
    };
  }
});

// packages/react/lib/message/MPopover.tsx
/**
 * @description react version MPopover
 * @author 阿怪
 * @date 2023/2/21 09:34
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { PopoverProps, usePopover } from '@shuimo-design/core';
import { Slot } from '../types';
import { cr } from '../../tools/coreRender';
import { useRef } from 'react';


export default function MPopover(props: PopoverProps & Slot) {
  const { getTemplate } = usePopover();

  const popoverRef = useRef<HTMLElement>();
  const contentRef = useRef<HTMLElement>();

  return cr(getTemplate({
    ref: { popoverRef, contentRef }
  }), props);
}
