// packages/vue/lib/message/MPopover.tsx
/**
 * @description MPopover
 * @author youus
 * @date 2022/4/3 18:07
 * @version v2.0.0-process
 *
 * Hello, humor
 * v2.0.0-process 阿怪 准备重构，搭建模版
 */
import { computed, defineComponent, onMounted, ref } from 'vue';
import { PopoverImpl, usePopover } from '@shuimo-design/core/lib/message/popover/usePopover';
import { props } from '@shuimo-design/core/lib/message/popover/api';
import useTeleport from '../../composition/useTeleport';


export default defineComponent({
  name: 'MPopover',
  props,
  emits: ['open:popper', 'close:popper', 'update:show'],
  setup(props, { slots, emit }) {
    //
    // if (!slots.content) {
    //   console.error('MPopover: content is required');
    //   return;
    // }
    //
    // if (!slots.default) {
    //   console.error('MPopover: trigger is required');
    //   return;
    // }


    const popoverRef = ref<HTMLElement>();
    const contentRef = ref<HTMLElement>();
    const popperInstance = ref<PopoverImpl>();
    const { createPopover, getContent } = usePopover();


    const styleComputed = computed(() => popperInstance.value?.style);
    const handleClick = async () => {
      popperInstance.value?.toggle();
    };

    onMounted(() => {
      popperInstance.value = createPopover(popoverRef.value, contentRef.value, {
        ...props.popper,
        placement: props.placement
      });
    });


    return () => {
      const content = slots.content();

      return <div class="m-popover">
        <div class="m-popover-default-wrapper"
             ref={popoverRef}
             onClick={handleClick}>
          {slots.default()}
        </div>
        <div class="m-popover-content" ref={contentRef} style={styleComputed.value}>
          {getContent(props, popperInstance.value, content, useTeleport)}
        </div>
      </div>;
    };
  }
});

// packages/react/lib/message/MPopover.tsx
/**
 * @description react version MPopover
 * @author 阿怪
 * @date 2023/2/21 09:34
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */

import React, { useEffect, useRef, useState } from 'react';
import { PopoverProps } from '@shuimo-design/core/lib/message/popover';
import { Slot } from '../../types';
import { PopoverImpl, usePopover } from '@shuimo-design/core/lib/message/popover/usePopover';
import { props as popoverProps } from '@shuimo-design/core/lib/message/popover/api';
import '@shuimo-design/core/lib/message/popover/popover.css';
import { getSlot, withDefault } from '../../base/tools';
import useTeleport from '../../base/useTeleport';

export default function MPopover(baseProps: PopoverProps & Slot) {
  const props = withDefault(baseProps, popoverProps);

  const styleState = useState({});
  const { createPopover, getContent } = usePopover({ style: styleState });

  const popoverRef = useRef(null);
  const contentRef = useRef(null);


  const [content, active] = getSlot(props, 'content');

  const [popperInstance, setPopperInstance] = useState<PopoverImpl | null>(null);

  useEffect(() => {
    setPopperInstance(createPopover(popoverRef.current!, contentRef.current!, {
      ...props.popper,
      placement: props.placement
    }));
  }, [popoverRef, contentRef]);

  const handleClick = async () => {
    popperInstance?.toggle();
  };


  return <div className="m-popover">
    <div className="m-popover-default-wrapper"
         ref={popoverRef}
         onClick={() => handleClick()}>
      {active}
    </div>
    <div className="m-popover-content" ref={contentRef} style={styleState[0]}>
      {getContent(props, content, useTeleport, popperInstance)}
    </div>
  </div>;
}
