// packages/react/lib/base/MSelect.tsx
/**
 * @description react version select
 * @author 阿怪
 * @date 2023/05/11 17:12
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/select/select.css';
import { SelectProps } from '@shuimo-design/core/lib/base/select';

export default function MSelect(props: SelectProps ) {


  return ;
}

// headless/components/base/select/MSelect.tsx
/**
 * @description headless select
 * @author 阿怪
 * @date 2024/11/28 16:27
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { SelectCore } from '@shuimo-design/ui-core';
import { defineComponent } from 'vue';
import { SelectProps } from '@shuimo-design/ui-core/components/base/select/props';


const props = SelectCore.props;

export default defineComponent((_props: SelectProps) => {

  const props = _props as Required<SelectProps>;

  return () => {

    return ;
  };

}, {
  name: 'MSelect',
  props,
});
