// packages/react/lib/other/MDarkMode.tsx
/**
 * @description react version MDarkMode
 * @author 阿怪
 * @date 2023/4/25 19:12
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { useState } from 'react';
import { DarkModeProps } from '@shuimo-design/core/lib/other/darkMode';
import { useDarkMode } from '@shuimo-design/core/lib/other/darkMode/useDarkMode';
import '@shuimo-design/core/lib/other/darkMode/darkMode.css';

export default function MDarkMode(props: DarkModeProps) {
  const { onMountedHook, toggleDarkMode } = useDarkMode();

  let isDarkMode = props.value;
  const clickHandler = () => {
    isDarkMode = !isDarkMode;
    toggleDarkMode({ value: !isDarkMode });
  };

  onMountedHook();

  const svg = <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 520" className="m-dark-mode-svg"
                   strokeWidth="1">
    <title>Dark Mode</title>
    <filter id="outset-shadow" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="20" floodColor="black"/>
    </filter>
    <filter id="outset-shadow-white" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="20" floodColor="white"/>
    </filter>
    <path
      className="svg-black"
      transform="translate(0)"
      fill="#000000"/>
    <path
      className="svg-white"
      transform="translate(0) rotate(180, 250, 250)"
      fill="#FFFFFF"/>
    <path
      className="svg-black dark-hidden"
      transform="translate(0)"
      fill="#000000"/>
    <circle className="svg-black" cx="250" cy="375" r="40"/>
    <circle className="svg-white" cx="250" cy="125" r="40" fill="#fff"/>
  </svg>;


  return <div className="m-dark-mode"
              onClick={() => clickHandler()}>
    {svg}
  </div>;

}

// packages/vue/lib/other/MDarkMode.tsx
/**
 * @description dark mode component
 * @author 阿怪
 * @date 2023/4/25 20:06
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * todo fix feDropShadow warning
 */
import { h, defineComponent, ref, onMounted } from 'vue';
import { props } from '@shuimo-design/core/lib/other/darkMode/api';
import { useDarkMode } from '@shuimo-design/core/lib/other/darkMode/useDarkMode';

export default defineComponent({
  name: 'MDarkMode',
  props: {
    modelValue: props.value
  },
  emits: ['update:modelValue'],
  setup: (props, { emit }) => {

    const value = ref(props.modelValue ?? false);
    const { onMountedHook, toggleDarkMode } = useDarkMode();

    const clickHandler = () => {
      value.value = !value.value;
      emit('update:modelValue', value.value);
      toggleDarkMode({ value: value.value });
    };

    onMounted(() => {
      onMountedHook();
    });

    return () => {
      const svg = <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 520" class="m-dark-mode-svg"
                       stroke-width="1">
        <title>Dark Mode</title>
        <filter id="outset-shadow" x="-50%" y="-50%" width="200%" height="200%">
          {h('feDropShadow', { dx: 0, dy: 0, stdDeviation: 20, floodColor: 'black' })}
        </filter>
        <filter id="outset-shadow-white" x="-50%" y="-50%" width="200%" height="200%">
          {h('feDropShadow', { dx: 0, dy: 0, stdDeviation: 20, floodColor: 'white' })}
        </filter>
        <path
          class="svg-black"
          transform="translate(0)"
          fill="#000000"/>
        <path
          class="svg-white"
          transform="translate(0) rotate(180, 250, 250)"
          fill="#FFFFFF"/>
        <path
          class="svg-black dark-hidden"
          transform="translate(0)"
          fill="#000000"/>
        <circle class="svg-black" cx="250" cy="375" r="40"/>
        <circle class="svg-white" cx="250" cy="125" r="40" fill="#fff"/>
      </svg>;


      return <div class="m-dark-mode"
                  onClick={(e: MouseEvent) => clickHandler()}>
        {svg}
      </div>;
    };
  }
});
