// packages/vue/lib/base/checkbox/MCheckbox.tsx
/**
 * @description MCheckbox
 * @author youus
 * @date 2022/4/7 00:01
 * @version v1.0.1
 *
 * Hello, humor
 *
 * v1.0.1 修复checkbox的slot支持
 * v2.0.0 阿怪 upgrade to core version
 */
import { defineComponent, ref, watch } from 'vue';
import { props } from '@shuimo-design/core/lib/base/checkbox/api';
import { getNewModelValue, initChecked } from '@shuimo-design/core/lib/base/checkbox/useCheckbox';
import { notEmpty } from '@shuimo-design/tools/empty';

export default defineComponent({
  name: 'MCheckbox',
  props,
  emits: ['change', 'update:modelValue'],
  setup(props, { emit, slots }) {

    const checked = ref(initChecked(props));

    watch(() => [props.modelValue, props.checked, props.value], () => {
      checked.value = initChecked(props);
    });

    const onClick = (e: MouseEvent) => {
      e.stopPropagation();
      if (props.disabled) {
        return;
      }
      checked.value = !checked.value;
      const newVal = getNewModelValue(props, checked.value);
      emit('change', newVal);
      emit('update:modelValue', newVal);
    };

    return () => {
      const label = <label class="m-checkbox-slot">
        {notEmpty(props.label) ? <span>{props.label}</span> : slots.default?.()}
      </label>;

      return <div class={['m-checkbox', { 'm-disabled': props.disabled }]} onClick={onClick}>
        <input type="checkbox" checked={checked.value}/>
        <div class="m-checkbox-checkbox"/>
        {
          props.indeterminate ? <div class="m-checkbox-checkbox-indeterminate"/> :
            checked.value ? <div class="m-checkbox-checkbox-inner "/> : null
        }
        {label}
      </div>;
    };
  }
});

// packages/lit/lib/base/MCheckBox.ts
/**
 * @description checkbox component
 * @author 阿怪
 * @date 2023/1/3 16:54
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */

import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { CheckboxProps } from '@shuimo-design/core/lib/base/checkbox';
import { initChecked } from '@shuimo-design/core/lib/base/checkbox/useCheckbox';
import { props } from '@shuimo-design/core/lib/base/checkbox/api';
import { notEmpty } from '@shuimo-design/tools/empty';
import style from '@shuimo-design/core/lib/base/checkbox/checkbox.css?inline';

@createMElement({
  name: 'checkbox',
  props
})
export default class MCheckBox extends LitElement implements CheckboxProps {

  checked?: boolean | undefined;
  disabled?: boolean;
  indeterminate?: boolean;
  label?: string;
  value?: string | number;
  modelValue?: boolean | undefined;

  static styles = unsafeCSS(style);

  onChange() {
    this.checked = !this.checked;
    this.dispatchEvent(new Event('change'));
  }

  onClick() {
    this.checked = !this.checked;
    this.dispatchEvent(new Event('click'));
  }

  private getInput() {
    const checked = initChecked(this as Required<CheckboxProps>);
    return html`<input type="checkbox" checked=${checked}/>`;
  }

  private getCheckboxInner() {
    return html`<div class="m-checkbox-checkbox-inner"/>`;
  }

  private getSlot() {
    return notEmpty(this.label) ?
      html`<span>{props.label}</span>` : html`<slot></slot>`;
  }

  private getLabel() {
    return html`<label class="m-checkbox-slot">
      ${this.getSlot()}
    </label>`;
  }

  render() {
    return html`
      <div class="m-checkbox"
           @click=${this.onClick}
           @change=${this.onChange}>
        ${this.getInput()}
        <div class="m-checkbox-checkbox"/>
        ${this.checked ? this.getCheckboxInner() : null}
        ${this.getLabel()}
      </div>`;
  }
}
