// packages/react/lib/base/MInput.tsx
/**
 * @description react version MInput
 * @author 阿怪
 * @date 2023/2/13 02:19
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/input/input.css';
import { InputEvents, InputProps } from '@shuimo-design/core/lib/base/input';
import MBorder from '../template/MBorder';
import { HTMLElementEvent } from '@shuimo-design/types';

export default function MInput(props: InputProps & InputEvents) {

  const isInput = props.type !== 'textarea';
  const domType = isInput ? 'input' : 'textarea';
  const borderClass = [
    'm-input',
    !isInput ? 'm-textarea' : '',
    props.disabled ? 'm-input-disabled' : ''
  ].join(' ');

  const dom = React.createElement(domType, {
    autoFocus: props.autofocus,
    value: props.value,
    placeholder: props.placeholder,
    disabled: props.disabled,
    readOnly: props.readonly,
    className: isInput ? 'm-input-inner' : 'm-textarea-inner',
    onInput: (e: HTMLElementEvent<HTMLInputElement>) => {
      if (props.disabled) {e.preventDefault();}
      props.onInput?.(e);
    },
    onFocus: (e: FocusEvent) => {
      if (props.disabled) {e.preventDefault();}
      props.onFocus?.(e);
    },
    onBlur: (e: FocusEvent) => {
      if (props.disabled) {e.preventDefault();}
      props.onBlur?.(e);
    },
    ...(isInput ? {} : { rows: 10 })
  });

  return <MBorder className={borderClass}>
    {dom}
  </MBorder>;
}

// packages/lit/lib/base/MInput.ts
/**
 * @description shuimo web component input
 * @author 阿怪
 * @date 2023/1/1 00:31
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { html, LitElement, unsafeCSS, TemplateResult } from 'lit';
import { eventOptions } from 'lit/decorators.js';
import { createMElement } from '../../base/createElement';
import { props } from '@shuimo-design/core/lib/base/input/api';
import { InputProps } from '@shuimo-design/core/lib/base/input';
import { HTMLElementEvent } from '@shuimo-design/types';
import style from '@shuimo-design/core/lib/base/input/input.css?inline';

@createMElement({
  name: 'input',
  props
})
export default class MInput extends LitElement implements InputProps {

  autofocus: boolean = false;
  disabled: boolean = false;
  value: string | number = '';
  placeholder: string = '';
  readonly: boolean = false;
  type: string = 'text';

  static styles = unsafeCSS(style);

  @eventOptions({ passive: true })
  onInput(e: HTMLElementEvent<HTMLInputElement>) {
    this.value = e.target.value;
  }

  withBorder(info: TemplateResult) {
    return html`
      <m-border
          class="${[
        'm-input',
        this.type === 'textarea' ? 'm-textarea' : '',
        this.disabled ? 'm-input-disabled' : ''
      ].join(' ')}">
        ${info}
      </m-border>`;
  }

  getTextarea() {
    return html`
      <textarea class="m-textarea-inner"
                rows="10"
                .autofocus="${this.autofocus}"
                .value="${this.value}"
                .placeholder="${this.placeholder}"
                .disabled="${this.disabled}"
                .readOnly="${this.readonly}"
                @input="${this.onInput}"/>
    `;
  }

  getInput() {
    return html`
      <input class="m-input-inner"
             .autofocus="${this.autofocus}"
             .value="${this.value}"
             .placeholder="${this.placeholder}"
             .disabled="${this.disabled}"
             .readOnly="${this.readonly}"
             @input="${this.onInput}"/>
    `;
  }

  render() {
    return this.withBorder(
      this.type === 'textarea' ? this.getTextarea() : this.getInput()
    );
  }
}
