// packages/react/lib/base/MSwitch.tsx
/**
 * @description react version MSwitch
 * @author 阿怪
 * @date 2023/2/18 22:07
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 * todo click event
 */
import React from 'react';
import { useState } from 'react';
import { SwitchEvents, SwitchProps } from '@shuimo-design/core/lib/base/switch';
import { isEmpty } from '@shuimo-design/tools/empty';
import { Slot } from '../../types';
import '@shuimo-design/core/lib/style/global.css';
import '@shuimo-design/core/lib/base/switch/switch.css';


export default function MSwitch(props: SwitchProps & SwitchEvents & Slot) {

  let baseActiveValue = props.activeValue;
  let baseInactiveValue = props.inactiveValue;

  const isBoolean = typeof props.value === 'boolean';

  if (isBoolean) {
    // 如果activeValue和inactiveValue都为空
    if (isEmpty(props.activeValue) && isEmpty(props.inactiveValue)) {
      baseActiveValue = true;
      baseInactiveValue = false;
    }
  }

  const [activeValue, setActiveValue] = useState(baseActiveValue);
  const [inactiveValue, setInactiveValue] = useState(baseInactiveValue);

  const isActive = props.value === activeValue;

  const changeSwitch = () => {

  }

  const getInfo = (key: keyof Pick<SwitchProps, 'activeInfo' | 'inactiveInfo'>) => {
    // if (props.children[key]) {
    //   return slots[key]!();
    // }
    // return <span class="m-switch-span">{props[key]}</span>;
    return <span className="m-switch-span">{props[key]}</span>;
  };

  return <div className={[
    'm-switch',
    isActive ? 'm-switch-active' : 'm-switch-inactive',
    props.loading ? 'm-switch-loading' : '',
    props.disabled ? 'm-switch-disabled' : ''
  ].join(' ')}>
    {getInfo('activeInfo')}
    <div className="m-switch-main">
      <div className="m-switch-core" onClick={changeSwitch}>
        <div className="m-switch-core-border"></div>
      </div>
    </div>
    {getInfo('inactiveInfo')}
  </div>
}

// packages/lit/lib/base/MSwitch.ts
/**
 * @description web-component version switch
 * @author 阿怪
 * @date 2023/2/18 16:10
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * todo fix loading css,click event
 */

import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { SwitchProps } from '@shuimo-design/core/lib/base/switch';
import { props } from '@shuimo-design/core/lib/base/switch/api';
import style from '@shuimo-design/core/lib/base/switch/switch.css?inline';
import { getIsActive, switchIsBoolean } from '@shuimo-design/core/lib/base/switch/useSwitch';
import { isEmpty } from '@shuimo-design/tools/empty';

@createMElement({
  name: 'switch',
  props
})
export default class MSwitch extends LitElement implements SwitchProps {
  activeInfo: string = '';
  activeValue: any;
  disabled: boolean = false;
  inactiveInfo: string = '';
  inactiveValue: any;
  loading?: boolean;
  onControl: boolean = false;
  value: any;

  static styles = unsafeCSS(style);

  constructor() {
    super();
    const isBoolean = this.isBoolean;
    if (isBoolean) {
      // 如果activeValue和inactiveValue都为空
      if (isEmpty(this.activeValue) && isEmpty(this.inactiveValue)) {
        this.activeValue = true;
        this.inactiveValue = false;
      }
    }
  }

  onClick(e: MouseEvent) {
    this.value = !this.value;
    this.dispatchEvent(new InputEvent('input'));
  }

  getInfo(key: keyof Pick<SwitchProps, 'activeInfo' | 'inactiveInfo'>) {
    if (this[key]) {
      return html`<span class="m-switch-span">${this[key]}</span>`;
    }
    return html`
      <slot name="${key}">`;
  };


  changeSwitch() {
    this.value = !this.value;
  }


  get isBoolean() {
    return switchIsBoolean(this.value);
  }

  get isActive() {
    return getIsActive(this.value, this.activeValue);
  }


  render() {
    return html`
      <div class=${[
        'm-switch',
        this.isActive ? 'm-switch-active' : 'm-switch-inactive',
        this.loading ? 'm-switch-loading' : '',
        this.disabled ? 'm-switch-disabled' : ''
      ].join(' ')}>
        ${this.getInfo('activeInfo')}
        <div class="m-switch-main">
          <div class="m-switch-core" @click=${this.changeSwitch}>
            <div class="m-switch-core-border"></div>
          </div>
        </div>
        ${this.getInfo('inactiveInfo')}
      </div>`;
  }


}
