// packages/react/lib/base/MButton.tsx
/**
 * @description
 * @author 阿怪
 * @date 2023/2/7 17:44
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/button/button.css';
import { ButtonEvents, ButtonProps } from '@shuimo-design/core/lib/base/button';
import { Slot } from '../../types';


export default function MButton(props: ButtonProps & ButtonEvents & Slot) {

  const domType = props.link ? 'a' : 'button';
  return React.createElement(domType, {
    className: [
      'm-button',
      props.disabled ? 'm-button-disabled' : undefined,
      `m-button-${props.type ?? 'default'}`
    ].filter(e => e).join(' '),
    disabled: props.disabled,
    onClick: (e:MouseEvent)=>{
      if(props.disabled){
        e.preventDefault();
      }
      props.onClick?.(e);
    }
  }, props.children ?? props.text);
}

// headless/components/base/button/MButton.tsx
/**
 * @description headless button
 * @author 阿怪
 * @date 2024/12/16 09:44
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent, h } from 'vue';
import { ButtonCore } from '@shuimo-design/ui-core';
import { ButtonProps } from '@shuimo-design/ui-core/components/base/button/props';
import './button.css';

const { props, useButton } = ButtonCore;

export default defineComponent((props: ButtonProps, ctx) => {
  return () => {
    const { domType, slot, domProps } = useButton(props, ctx);
    return h(domType, domProps, slot);
  };
}, {
  name: 'MButton',
  props,
});
