// packages/vue/lib/template/MFormItem.tsx
/**
 * @description vue version formItem
 * @author 阿怪
 * @date 2023/05/04 20:36
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent, h } from 'vue';
import { formItemProps } from '@shuimo-design/core/lib/template/form/api';

export default defineComponent({
  name: 'MFormItem',
  props: formItemProps,
  setup: (props, { slots }) => {
    return () => {
      const labelSlot = slots.label ? slots.label() : props.label;
      const defaultSlot = slots.default ? slots.default() : '';
      return <div class="m-form-item">
          <label for={props.prop} class="m-form-item-label">
            {labelSlot}
          </label>
          <div class="m-form-item-content">{defaultSlot}</div>
        </div>;
    };
  }
});

// packages/lit/lib/template/MFormItem.ts
/**
 * @description web-component version formItem
 * @author 阿怪
 * @date 2023/03/10 02:30
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { formItemProps } from '@shuimo-design/core/lib/template/form/api';
import { FormItemProps } from '@shuimo-design/core/lib/template/form/formItem';
import style from '@shuimo-design/core/lib/template/form/formItem.css?inline';

@createMElement({
  name: 'form-item',
  props: formItemProps
})
export default class extends LitElement implements FormItemProps {

  label: string = '';
  prop: string = '';

  static styles = unsafeCSS(style);

  get labelSlot() {
    return this.label?this.label:html`<slot name="label"></slot>`;
  }

  get defaultSlot() {
    return html`<slot></slot>`;
  }

  render() {
    return html`<div class="m-form-item">
      <label for=${this.prop} class="m-form-item-label">
        ${this.labelSlot}
      </label>
      <div class="m-form-item-content">${this.defaultSlot}</div>
    </div>`;
  }

}
