// headless/components/base/radio/MRadio.tsx
/**
 * @description headless radio
 * @author 阿怪
 * @date 2025/02/25 00:00
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent, ref } from 'vue';
import { RadioCore } from '@shuimo-design/ui-core';
import { initChecked, getNewModelValue, createRadioId } from '@shuimo-design/ui-core/components/base/radio/useRadio.ts';
import { RadioProps } from '@shuimo-design/ui-core/components/base/radio/props';
import { notEmpty } from '@shuimo-design/ui-core/tools';
import './radio.css';

export default defineComponent((_props: RadioProps, { emit, slots }) => {
  const props = _props as Required<RadioProps>;
  const checked = ref(initChecked(props));
  const id = createRadioId();

  const onClick = () => {
    checked.value = !checked.value;
    emit('update:modelValue', getNewModelValue(props, checked.value));
  };

  return () => {
    const slotsDefault = slots.default ? slots.default() : (notEmpty(props.label) ? <span>{props.label}</span> : null);

    return <label class="m-radio" for={id}>
      <input type="radio" class="m-radio-input" id={id}
             name={props.name} checked={checked.value} value={props.value}
             onClick={onClick}/>
      {slotsDefault}
    </label>;
  };
}, {
  name: 'MRadio',
  props: RadioCore.props,
  emits: ['update:modelValue'],
});

// packages/react/lib/base/MRadio.tsx
/**
 * @description react version MRadio
 * @author 阿怪
 * @date 2023/2/26 20:05
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { useState } from 'react';
import { RadioEvents, RadioProps } from '@shuimo-design/core/lib/base/radio';
import { Slot } from '../../types';
import { initChecked } from '@shuimo-design/core/lib/base/radio/useRadio';
import { withDefault } from '../../base/tools';
import { props as radioProps } from '@shuimo-design/core/lib/base/radio/api';
import { getNewModelValue, createRadioId } from '@shuimo-design/core/lib/base/radio/useRadio';
import '@shuimo-design/core/lib/base/radio/radio.css';

export default function MRadio(baseProps: RadioProps & RadioEvents & Slot) {
  const props = withDefault(baseProps, radioProps);

  const [checked] = useState(initChecked(props));

  const slotsDefault = props.children ?? props.label;
  const onClick = (e: any) => {
    baseProps.onClick?.(e, getNewModelValue(props, checked));
  };
  const id = createRadioId();


  return <label className="m-radio" htmlFor={id}>
    <input type="radio" className="m-radio-input" id={id}
           name={props.name} defaultChecked={checked} value={props.value}
           onClick={onClick}/>
    {slotsDefault}
  </label>;

}
