// packages/vue/lib/base/MRadio.tsx
/**
 * @description MRadio
 * @author 望海潮
 * @date 2022-03-23 18:24:55
 * @description radio单选框
 */

import { defineComponent, ref } from 'vue';
import { props } from '@shuimo-design/core/lib/base/radio/api';
import { createRadioId, getNewModelValue, initChecked } from '@shuimo-design/core/lib/base/radio/useRadio';

export default defineComponent({
  name: 'MRadio',
  props,
  setup(props, { emit, slots }) {
    const checked = ref(initChecked(props));
    const onClick = () => {
      checked.value = !checked.value;
      emit('update:modelValue', getNewModelValue(props, checked.value));
    };
    const id = createRadioId();

    return () => {
      const slotsDefault = slots.default ? slots.default() : props.label;

      return <label class="m-radio" for={id}>
        <input type="radio" class="m-radio-input" id={id}
               name={props.name} checked={checked.value} value={props.value}
               onClick={onClick}/>
        {slotsDefault}
      </label>;
    };
  }
});

// packages/react/lib/base/MRadio.tsx
/**
 * @description react version MRadio
 * @author 阿怪
 * @date 2023/2/26 20:05
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { useState } from 'react';
import { RadioEvents, RadioProps } from '@shuimo-design/core/lib/base/radio';
import { Slot } from '../../types';
import { initChecked } from '@shuimo-design/core/lib/base/radio/useRadio';
import { withDefault } from '../../base/tools';
import { props as radioProps } from '@shuimo-design/core/lib/base/radio/api';
import { getNewModelValue, createRadioId } from '@shuimo-design/core/lib/base/radio/useRadio';
import '@shuimo-design/core/lib/base/radio/radio.css';

export default function MRadio(baseProps: RadioProps & RadioEvents & Slot) {
  const props = withDefault(baseProps, radioProps);

  const [checked] = useState(initChecked(props));

  const slotsDefault = props.children ?? props.label;
  const onClick = (e: any) => {
    baseProps.onClick?.(e, getNewModelValue(props, checked));
  };
  const id = createRadioId();


  return <label className="m-radio" htmlFor={id}>
    <input type="radio" className="m-radio-input" id={id}
           name={props.name} defaultChecked={checked} value={props.value}
           onClick={onClick}/>
    {slotsDefault}
  </label>;

}
