// packages/lit/lib/base/MRadio.ts
/**
 * @description input component
 * @author 阿怪
 * @date 2023/2/26 14:03
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * todo fix name
 */
import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { RadioProps } from '@shuimo-design/core/lib/base/radio';
import { props } from '@shuimo-design/core/lib/base/radio/api';
import { createRadioId, initChecked } from '@shuimo-design/core/lib/base/radio/useRadio';
import { notEmpty } from '@shuimo-design/tools/empty';
import style from '@shuimo-design/core/lib/base/radio/radio.css?inline';

@createMElement({
  name: 'radio',
  props
})
export default class MRadio extends LitElement implements RadioProps {
  checked?: boolean | null = false;
  label: string | number = '';
  modelValue: any = undefined;
  name: string = '';
  value: any = undefined;

  static styles = unsafeCSS(style);


  id = createRadioId();

  onClick(e: MouseEvent) {
    // if (this.disabled) {
    //   e.preventDefault();
    // }
  }

  getSlotsDefault(){
    return notEmpty(this.label)?this.label:html`<slot/>`;
  }

  render() {
    const checked = initChecked(this as Required<RadioProps>);
    return html`<label class="m-radio" for=${this.id}>
      <input type="radio" class="m-radio-input" id=${this.id}
             name=${this.name} .checked=${checked} value=${this.value}
             @click=${this.onClick}/>
      ${this.getSlotsDefault()}
    </label>`
  }

}

// packages/react/lib/base/MRadio.tsx
/**
 * @description react version MRadio
 * @author 阿怪
 * @date 2023/2/26 20:05
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { useState } from 'react';
import { RadioEvents, RadioProps } from '@shuimo-design/core/lib/base/radio';
import { Slot } from '../../types';
import { initChecked } from '@shuimo-design/core/lib/base/radio/useRadio';
import { withDefault } from '../../base/tools';
import { props as radioProps } from '@shuimo-design/core/lib/base/radio/api';
import { getNewModelValue, createRadioId } from '@shuimo-design/core/lib/base/radio/useRadio';
import '@shuimo-design/core/lib/base/radio/radio.css';

export default function MRadio(baseProps: RadioProps & RadioEvents & Slot) {
  const props = withDefault(baseProps, radioProps);

  const [checked] = useState(initChecked(props));

  const slotsDefault = props.children ?? props.label;
  const onClick = (e: any) => {
    baseProps.onClick?.(e, getNewModelValue(props, checked));
  };
  const id = createRadioId();


  return <label className="m-radio" htmlFor={id}>
    <input type="radio" className="m-radio-input" id={id}
           name={props.name} defaultChecked={checked} value={props.value}
           onClick={onClick}/>
    {slotsDefault}
  </label>;

}
