// headless/components/base/tag/MTag.tsx
/**
 * @description headless tag
 * @author 阿怪
 * @date 2025/02/25 00:00
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent } from 'vue';
import { TagCore } from '@shuimo-design/ui-core';
import { TagProps } from '@shuimo-design/ui-core/components/base/tag/props';
import './tag.css';

const { props } = TagCore;

export default defineComponent((props: TagProps, { slots }) => {
  return () => {
    return <div class={['m-tag', `m-tag-${props.type}`]}>
      {slots.default?.() ?? ''}
    </div>;
  };
}, {
  name: 'MTag',
  props,
});

// packages/react/lib/base/MTag.tsx
/**
 * @description react version MTag
 * @author 阿怪
 * @date 2023/3/1 01:21
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/tag/tag.css';
import { TagProps } from '@shuimo-design/core/lib/base/tag';
import { Slot } from '../../types';

export default function MTag(props: TagProps & Slot) {

  return <div className={['m-tag', `m-tag-${props.type ?? 'default'}`].join(' ')}>
    <div className="m-tag-left"/>
    <div className="m-tag-main">
      {props.children}
    </div>
    <div className="m-tag-right"/>
  </div>;
}
