// packages/react/lib/message/MConfirm.tsx
/**
 * @description react version confirm
 * @author 阿怪
 * @date 2023/05/10 20:04
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { ReactElement } from 'react';
import { createRoot } from 'react-dom/client';
import '@shuimo-design/core/lib/message/confirm/confirm.css';
import { ConfirmProps, IConfirm } from '@shuimo-design/core/lib/message/confirm';
import { useConfirm } from '@shuimo-design/core/lib/message/confirm/useConfirm';
import useModel from '../../base/useModel';
import MButton from '../base/MButton';
import MBorder from '../template/MBorder';

const Confirm: IConfirm = async config => {
  const { ConfirmImpl } = useConfirm((options) => {
    const { confirmDiv, _content, confirm,cancel, bodyDom } = options;
    const MConfirm: React.FC<ConfirmProps> = props => {
      const {
        getModel,
        handleModelClickPropagation
      } = useModel({ mask: { show: true }, ...props, teleport: { to: confirmDiv }, visible: true });

      const confirmBtn = <MButton type="primary" onClick={confirm}>确定</MButton>;
      const cancelBtn = <MButton onClick={cancel}>取消</MButton>;

      const withBorder = (slot: React.ReactNode, appendClass?: string) => <MBorder className={appendClass}>
        {slot}
      </MBorder>;

      const getConfirm = () => {
        return getModel(<div className="m-confirm">
          {withBorder(<div onClick={handleModelClickPropagation}>
            <div className="m-confirm-inner">
              <span>{_content}</span>
              <div className="m-confirm-button">
                {confirmBtn}
                {cancelBtn}
              </div>
            </div>
          </div>)}
        </div>);
      };

      return getConfirm() as ReactElement;
    };

    const confirmNode = React.createElement(MConfirm);
    createRoot(confirmDiv).render(confirmNode);
    bodyDom.appendChild(confirmDiv);

  });

  return ConfirmImpl(config);
};

export default Confirm;

// lib/components/message/confirm/MConfirm.tsx
/**
 * @description vue version confirm
 * @author 阿怪
 * @date 2023/05/10 20:04
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { createApp, h, VNode } from 'vue';
import useModel from '../../../../lib/compositions/useModel';
import { ConfirmProps, IConfirm } from './index';
import { useConfirm } from './useConfirm.ts';
import { props } from './api.ts';
import MButton from '../../base/button/MButton.tsx';
import MBorder from '../../template/border/MBorder.tsx';
import './confirm.css';

const Confirm: IConfirm = async config => {
  const { ConfirmImpl } = useConfirm(options => {
    const { confirmDiv, _content, confirm, cancel, bodyDom } = options;

    const confirmVNode = h({
      name: 'MConfirm',
      props,
      setup: (props: ConfirmProps, { emit }) => {


        const {
          getModel,
          handleModelClickPropagation,
        } = useModel({ ...props, teleport: { to: confirmDiv }, visible: true }, { emit });

        const confirmBtn = h(MButton, { text: '确定', type: 'primary', onClick: confirm });
        const cancelBtn = h(MButton, { text: '取消', onClick: cancel });

        const withBorder = (slot: VNode, appendClass?: string) => h(MBorder, {
          class: appendClass,
        }, () => slot);

        return () => {
          const getConfirm = () => {
            return getModel(withBorder(<div onClick={handleModelClickPropagation}>
              <div class="m-confirm-inner">
                <span>{props.content}</span>
                <div class="m-confirm-button">
                  {confirmBtn}
                  {cancelBtn}
                </div>
              </div>

            </div>, 'm-confirm'));
          };

          return getConfirm();
        };
      },
    });

    createApp(confirmVNode, { content: _content }).mount(confirmDiv);

    bodyDom.appendChild(confirmDiv);
  });
  return ConfirmImpl(config);
};

export default Confirm;
