// packages/react/lib/message/message/MMessage.tsx
/**
 * @description react version message
 * @author 阿怪
 * @date 2023/05/22 16:31
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { createElement, createRef, RefObject, useRef } from 'react';
import '@shuimo-design/core/lib/message/message/message.css';
import { useMessage } from '@shuimo-design/core/lib/message/message/useMessage';
import MMessageList from './MMessageList';
import { createRoot } from 'react-dom/client';
import { MessageIns } from '@shuimo-design/core/lib/message/message';
import MMessageItem from './MMessageItem';

type ReactMessageIns = MessageIns<typeof MMessageItem>;

const { initMessage } = useMessage();

export default initMessage({
  getIns: async direction => {
    const initMessageList = () => {
      return new Promise<RefObject<ReactMessageIns>>((resolve) => {
        const ref = createRef<ReactMessageIns>();
        const dom = <MMessageList direction={direction} ref={ref} resolveRef={() => resolve(ref)}/>;
        const wrapper = document.createElement('div');
        wrapper.classList.add('m-message-wrapper');
        createRoot(wrapper).render(dom);
        document.body.append(wrapper);
      });
    };
    const ref = await initMessageList();
    return ref.current as ReactMessageIns;
  },
  nextTick: async (resolve, messageListIns) => {
    resolve(undefined);
  }
});

// packages/vue/lib/message/message/MMessage.tsx
/**
 * @description message插件式组件
 * @author: qunbotop
 * @date 2022/5/16 4:37 下午
 * @version v3.0.0
 *
 * v2.0.1 message handler 提供返回
 * v3.0.0 refactor 阿怪
 */
import { MessageIns } from '@shuimo-design/core/lib/message/message';
import { ComponentPublicInstance, createApp, nextTick } from 'vue';
import { useMessage } from '@shuimo-design/core/lib/message/message/useMessage';
import MMessageList from './MMessageList';
import MMessageItem from './MMessageItem';

type VueMessageIns = MessageIns<InstanceType<typeof MMessageItem>> & ComponentPublicInstance;

let { initMessage } = useMessage<InstanceType<typeof MMessageItem>>();

const MMessage = initMessage({
  getIns: direction => {
    const wrapper = document.createElement('div');
    return createApp(MMessageList, { direction }).mount(wrapper) as VueMessageIns;
  },
  nextTick: async (resolve, messageListIns) => {
    await nextTick(() => {
      const { domList } = messageListIns;
      const dom = domList[domList.length - 1];
      resolve(dom);
    });
  }
});

export default MMessage;
