// packages/vue/lib/template/ricePaper/MRicePaper.tsx
/**
 * @description 宣纸背景组件
 * @author 阿怪
 * @date 2022/7/14 23:22
 * @version v1.0.1
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 * v1.0.1 默认改为冷色调，添加色调选项
 */
import { defineComponent } from 'vue';
import { props } from '@shuimo-design/core/lib/template/ricePaper/api';


export const MRicePaperOption = (styleNode?, slot?)=>{
  return {
    name: 'MRicePaper',
    props,
    setup(props, { slots }) {
      return () => {
        const mountainTemplate = props.mountain ? <div class="m-rice-paper-mountain"></div> : null;
        const craneTemplate = props.crane ? <div class="m-rice-paper-crane"></div> : null;

        return <div class={['m-rice-paper', { 'm-rice-paper-warm': !props.cold }]}>
          {styleNode}
          {mountainTemplate}
          {craneTemplate}
          <div class="m-rice-paper-main">
            {slot ?? slots.default?.()}
          </div>
        </div>;
      };
    }
  }
}

export default defineComponent(MRicePaperOption());

// packages/react/lib/template/MRicePaper.tsx
/**
 * @description react version rice paper component
 * @author 阿怪
 * @date 2023/2/7 02:18
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/template/ricePaper/ricePaper.css';
import { RicePaperProps } from '@shuimo-design/core/lib/template/ricePaper/index.d';
import { Slot } from '../../types';

export default function MRicePaper(props: RicePaperProps & Slot) {
  const mountainTemplate = props.mountain ? <div className="m-rice-paper-mountain"></div> : null;
  const craneTemplate = props.crane ? <div className="m-rice-paper-crane"></div> : null;


  return <div className={['m-rice-paper', !props.cold ? 'm-rice-paper-warm' : undefined].join(' ')}>
    {mountainTemplate}
    {craneTemplate}
    <div className="m-rice-paper-main">
      {props.children}
    </div>
  </div>

}
