// packages/lit/lib/template/MRicePaper.ts
/**
 * @description rice-paper component
 * @author 阿怪
 * @date 2022/12/17 13:32
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { RicePaperProps } from '@shuimo-design/core/lib/template/ricePaper/index.d';
import { props } from '@shuimo-design/core/lib/template/ricePaper/api';
import style from '@shuimo-design/core/lib/template/ricePaper/ricePaper.css?inline';

@createMElement({
  name: 'rice-paper',
  props
})
export default class MRicePaper extends LitElement implements RicePaperProps {

  cold: boolean = false;
  mountain: boolean = false;
  crane: boolean = false;

  static styles = unsafeCSS(style);

  mountainTemplate() {
    return this.mountain ? html`
      <div class="m-rice-paper-mountain"></div>` : '';
  }

  carneTemplate() {
    return this.crane ? html`
      <div class="m-rice-paper-crane"></div>` : '';
  }

  render() {
    return html`
      <div class="${['m-rice-paper', !this.cold ? 'm-rice-paper-warm' : undefined].join(' ')}">
        ${this.mountainTemplate()}
        ${this.carneTemplate()}
        <div class="m-rice-paper-main">
          <slot></slot>
        </div>
      </div>`;
  }
}

// packages/react/lib/template/MRicePaper.tsx
/**
 * @description react version rice paper component
 * @author 阿怪
 * @date 2023/2/7 02:18
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/template/ricePaper/ricePaper.css';
import { RicePaperProps } from '@shuimo-design/core/lib/template/ricePaper/index.d';
import { Slot } from '../../types';

export default function MRicePaper(props: RicePaperProps & Slot) {
  const mountainTemplate = props.mountain ? <div className="m-rice-paper-mountain"></div> : null;
  const craneTemplate = props.crane ? <div className="m-rice-paper-crane"></div> : null;


  return <div className={['m-rice-paper', !props.cold ? 'm-rice-paper-warm' : undefined].join(' ')}>
    {mountainTemplate}
    {craneTemplate}
    <div className="m-rice-paper-main">
      {props.children}
    </div>
  </div>

}
