// packages/vue/lib/template/MTable.tsx
/**
 * @description vue version table
 * @author 阿怪
 * @date 2023/03/11 13:49
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent } from 'vue';
import { props } from '@shuimo-design/core/lib/template/table/api';
import { useTable } from '@shuimo-design/core/lib/template/table/useTable';

export default defineComponent({
  name: 'MTable',
  props,
  setup: (props, { slots }) => {
    const { initTable } = useTable();

    return () => {

      const { thead, tbody } = initTable({
        empty: <div class="m-table-empty">暂无数据</div>,
        tbodyTr: data => <td class="m-td">{data}</td>,
        theadTh: label => <th class="m-th">{label}</th>,
        thead: ths => <thead class="m-thead">
        <tr>{ths}</tr>
        </thead>,
        tbody: trs => <tbody class="m-tbody">{trs}</tbody>,
        tbodyTrs: (tds, i) => <tr class="m-tr">{...tds}
          {i === 0 ? undefined : <td class="m-table-tbody-img"/>}
        </tr>
      }, slots.default(), props.data);


      const table = <table class="m-table-inner">
        {thead}
        {tbody}
      </table>;

      return <div class="m-table">
        <div class="m-table-header-img-top"/>
        <div class="m-table-header-img-bottom"/>
        <div class="m-table-wrap">
          {table}
        </div>
        <div class="m-table-border-img-bottom"/>
      </div>;

    };
  }
});

// packages/react/lib/template/MTable.tsx
/**
 * @description react version table
 * @author 阿怪
 * @date 2023/03/11 13:49
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/template/table/table.css';
import { TableProps } from '@shuimo-design/core/lib/template/table';
import { Slot } from '../../types';
import { useTable } from '@shuimo-design/core/lib/template/table/useTable';
import { withDefault } from '../../base/tools';
import { props as tableProps } from '@shuimo-design/core/lib/template/table/api';

export default function MTable(baseProps: TableProps & Slot) {
  const { initTable } = useTable();
  const props = withDefault(baseProps, tableProps);

  if (!props.children) {
    console.error('MTable: children is required');
    return null;
  }

  const { thead, tbody } = initTable<React.ReactElement>({
    empty: <div className="m-table-empty">暂无数据</div>,
    tbodyTr: data => <td className="m-td">{data}</td>,
    theadTh: label => <th key={`m-table-head-th-${label}`} className="m-th">{label}</th>,
    thead: ths => <thead className="m-thead">
    <tr>{ths}</tr>
    </thead>,
    tbody: trs => <tbody className="m-tbody">{trs}</tbody>,
    tbodyTrs: (tds, i) => <tr key={`m-table-colum-${i}`} className="m-tr">{...tds}
      {i === 0 ? undefined : <td className="m-table-tbody-img"/>}
    </tr>
  }, props.children as React.ReactNode[], props.data);

  const table = <table className="m-table-inner">
    {thead}
    {tbody}
  </table>;

  return <div className="m-table">
    <div className="m-table-header-img-top"/>
    <div className="m-table-header-img-bottom"/>
    <div className="m-table-wrap">
      {table}
    </div>
    <div className="m-table-border-img-bottom"/>
  </div>;
}
