// packages/vue/lib/template/MTableColumn.tsx
/**
 * @description vue version tableColumn
 * @author 阿怪
 * @date 2023/03/11 13:50
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { defineComponent } from 'vue';
import { props } from '@shuimo-design/core/lib/template/tableColumn/api';

export default defineComponent({
  name: 'MTableColumn',
  props
});

// packages/react/lib/template/MTableColumn.tsx
/**
 * @description react version tableColumn
 * @author 阿怪
 * @date 2023/03/11 13:50
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import { TableColumnProps } from '@shuimo-design/core/lib/template/tableColumn';
import { Slot } from '../../types';

export default function MTableColumn(props: TableColumnProps & Slot) {
  return  <></>;
}
