// apps/playground/vue/src/Base.vue
<template>
  <div class="flex">

    <div class="hidden">
      <div class="li">
        <m-li>hi</m-li>
        <m-li active>active li</m-li>
      </div>
      <div class="tag">
        <m-tag>hi</m-tag>
        <m-tag>primary</m-tag>
        <m-tag type="primary">primary</m-tag>
        <m-tag type="error">error</m-tag>
        <m-tag type="confirm">confirm</m-tag>
        <m-tag type="warning">warning</m-tag>
      </div>
      <div class="switch">
        <span>参数值为：{{ switchValue }}</span>
        <m-switch v-model="switchValue"/>
        <m-switch v-model="switchValue" loading/>
        <m-switch v-model="switchValue" disabled/>
      </div>
      <div class="radio">
        <span>radio:{{ radioVal }}</span>
        <br/>

        <m-radio v-model="radioVal" :label="radioLabel" name="hi" :value="radioLabel"/>
        <m-radio label="2" name="hi" value="2"/>
        <m-radio label="3" name="hi" value="2"/>
      </div>
      <div class="checkbox">
        <m-progress :value="20"/>
        <m-progress :value="44" show-info/>
        <m-progress :value="44" show-info>44</m-progress>

        <span>{{ checkboxVal }}</span>
        <br/>
        <m-checkbox/>
        <m-checkbox disabled></m-checkbox>
        <m-checkbox v-model="checkboxVal"></m-checkbox>
        <m-checkbox>slot</m-checkbox>
        <m-checkbox label="label"></m-checkbox>
        <m-checkbox label="label">replace by label</m-checkbox>
        <m-checkbox :checked="true">default checked</m-checkbox>
        <br/>
        <span>checkboxValNumber:{{ checkboxValNumber }}</span>
        <br/>
        <m-checkbox v-model="checkboxValNumber" :value="1">number value 1</m-checkbox>
        <br/>
        <m-checkbox v-model="checkboxValNumber" :value="2">number value 2</m-checkbox>
        <br/>
        <span>{{ checkboxObjectValue }}</span>
        <br/>
        <m-checkbox v-model="checkboxObjectValue" :value="checkboxObject">obj value</m-checkbox>
      </div>
      <div class="input">
        <span>{{ inputValue }}</span>
        <br/>
        <m-input v-model="inputValue"></m-input>
        <m-input readonly v-model="inputValue"></m-input>
        <m-input disabled v-model="inputValue"></m-input>
        <m-input type="textarea"></m-input>
      </div>
      <div class="button">
        <m-button @click="buttonClick" class="button-event">你好</m-button>
        <m-button type="error">error</m-button>
        <m-button type="primary">primary</m-button>
        <m-button type="confirm">confirm</m-button>
        <m-button type="warning">warning</m-button>
        <m-button link>link</m-button>
        <m-button @click="buttonClick" class="button-event" disabled>disabled</m-button>
        <m-button text="text！"></m-button>
      </div>
    </div>

    <div class="list">
      <m-list :data="stringList"/>
      <m-list :data="dataList">
        <template #default="{data}">
          <span>title:{{ data.title }}</span>
        </template>
      </m-list>
    </div>


  </div>
</template>

<script setup lang="ts">
/**
 * @description vue playground base
 * @author 阿怪
 * @date 2023/4/21 11:19
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { ref } from 'vue';

const buttonClick = () => {console.log('button click');};

const inputValue = ref('input value');

const checkboxVal = ref(true);
const checkboxValNumber = ref(1);
const checkboxObject = ref({ label: 'label', value: 'value' });
const checkboxObjectValue = ref();

const radioVal = ref('');
const radioLabel = ref('radio label');

const switchValue = ref(false);

const dataList = [
  { title: '轩辕剑', active: true },
  { title: '湛卢' },
  { title: '赤霄' }
];

const stringList = ['轩辕剑', '湛卢', '赤霄'];


</script>

<style scoped>

.hidden {
  display: none;
}

</style>

// apps/playground/react/src/Base.tsx
/**
 * @description
 * @author 阿怪
 * @date 2023/4/21 11:08
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { MButton, MCheckbox, MInput, MProgress, MRadio, MSwitch, MTag, MLi, MList } from '@shuimo-design/react/index';
import { useState } from 'react';

export default function Base() {
  const buttonClick = () => {console.log('button click');};

  const button = <div>
    <MButton onClick={buttonClick}>你好</MButton>
    <MButton type="error">error</MButton>
    <MButton type="primary">primary</MButton>
    <MButton type="confirm">confirm</MButton>
    <MButton type="warning">warning</MButton>
    <MButton link>link</MButton>
    <MButton disabled onClick={buttonClick}>disabled</MButton>
    <MButton text="text！"></MButton>
  </div>;


  const [inputVal, setVale] = useState('input value');
  const inputChange = (e: Event & { target: any }) => {
    setVale(e.target.value);
  };
  const input = <div>
    <span>{inputVal}</span>
    <br/>
    <MInput value={inputVal} onInput={inputChange}/>
    <MInput readonly value={inputVal} onInput={inputChange}/>
    <MInput disabled value={inputVal} onInput={inputChange}/>
    <MInput type="textarea"></MInput>
  </div>;


  const [checkboxVal, setCheckboxVal] = useState(true);
  const [checkboxValNumber, setCheckboxValNumber] = useState(1);
  const obj = { label: 'label', value: 'value' };
  const [checkboxObject, setCheckboxObject] = useState({
    value: obj
  });
  const checkboxChange = (e: any) => {
    setCheckboxVal(e);
  };

  const checkbox = <div className="checkbox">
    <span>{checkboxVal ? 'true' : 'false'}</span>
    <br/>
    <MCheckbox/>
    <MCheckbox disabled></MCheckbox>
    <MCheckbox modelValue={checkboxVal} onInput={checkboxChange}></MCheckbox>
    <MCheckbox>slot</MCheckbox>
    <MCheckbox label="label"></MCheckbox>
    <MCheckbox label="label">replace by label</MCheckbox>
    <MCheckbox checked={true}>default checked</MCheckbox>
    <br/>
    <span>checkboxValNumber:{checkboxValNumber}</span>
    <br/>
    <MCheckbox modelValue={checkboxValNumber} onInput={setCheckboxValNumber} value={1}>number value 1</MCheckbox>
    <br/>
    <MCheckbox modelValue={checkboxValNumber} onInput={setCheckboxValNumber} value={2}>number value 2</MCheckbox>
  </div>;


  const progress = <div className="progress">
    <MProgress value={20}></MProgress>
  </div>;


  const radio = <div className="radio">
    <MRadio name="hi"></MRadio>
    <MRadio label="label" name="hi"></MRadio>
    <MRadio label="label" name="hi">replace by label</MRadio>
  </div>

  const [switchVal, setSwitchVal] = useState(true);
  const switchDom = <div className="switch">
    <MSwitch value={switchVal}></MSwitch>
    <MSwitch value={switchVal} loading></MSwitch>
    <MSwitch value={switchVal} disabled></MSwitch>
  </div>

  const tagDom = <div className="tag">
    <MTag>hi</MTag>
    <MTag type="primary">primary</MTag>
    <MTag type="error">error</MTag>
    <MTag type="confirm">confirm</MTag>
    <MTag type="warning">warning</MTag>
  </div>

  const li = <div className="li">
    <MLi>hi</MLi>
    <MLi active>active li</MLi>
  </div>

  const dataList = [
    { title: '轩辕剑', active: true },
    { title: '湛卢' },
    { title: '赤霄' }
  ];

  const stringList = ['轩辕剑', '湛卢', '赤霄'];

  const listData = (data:{data:{title:string}})=>{
    return <span>{data.data.title}</span>
  }

  const list = <div className="list">
    <MList data={stringList}/>
    <MList data={dataList} children={listData}/>
  </div>


  return <div className="flex">
    {list}
  </div>;
}
