// apps/playground/src/Playground.vue
<template>
  <m-button :disabled="disabled" :type="type" @click="toggleType">按钮</m-button>
  <!--  <m-button>按钮2</m-button>-->
</template>

<script setup lang="ts">
/**
 * @description
 * @author 阿怪
 * @date 2022/12/10 14:08
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import { ref } from 'vue';

const disabled = ref(true);
const type = ref('confirm');
const toggleType = () => {
  type.value = type.value === 'confirm' ? 'error' : 'confirm';
};

</script>

<style scoped>

m-button {
  margin: 4px;
}

</style>

// apps/playground/react/src/Playground.tsx
/**
 * @description
 * @author 阿怪
 * @date 2023/2/6 17:10
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */

import { MButton } from '@shuimo-design/react/index';
import { useState } from 'react';

export default function Playground() {

  const [type, setType] = useState('primary');
  const [disabled, setDisabled] = useState(false);

  const clickButton = () => {
    console.log('hi',disabled);
    if (type === 'primary') {
      setType('warn');
      setDisabled(true);
    } else {
      setType('primary');
      setDisabled(false);
    }
  }

  const clickButton2 = () => {
    console.log('hello');
  }


  return (
    <>
      <MButton disabled={disabled} onClick={clickButton2}>hi</MButton>
      <MButton type="primary" onClick={clickButton}>hi</MButton>
    </>
  );
}
