// packages/react/lib/base/MButton.tsx
/**
 * @description
 * @author 阿怪
 * @date 2023/2/7 17:44
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React from 'react';
import '@shuimo-design/core/lib/base/button/button.css';
import { ButtonEvents, ButtonProps } from '@shuimo-design/core/lib/base/button';
import { Slot } from '../../types';


export default function MButton(props: ButtonProps & ButtonEvents & Slot) {

  const domType = props.link ? 'a' : 'button';
  return React.createElement(domType, {
    className: [
      'm-button',
      props.disabled ? 'm-button-disabled' : undefined,
      `m-button-${props.type ?? 'default'}`
    ].filter(e => e).join(' '),
    disabled: props.disabled,
    onClick: (e:MouseEvent)=>{
      if(props.disabled){
        e.preventDefault();
      }
      props.onClick?.(e);
    }
  }, props.children ?? props.text);
}

// packages/vue/lib/base/MButton.tsx
/**
 * @description 按钮组件
 * @author 阿怪
 * @date 2021/8/10 4:59 下午
 * @version v3.0.0
 *
 * 公司的业务千篇一律，复杂的代码好几百行。
 * v1.0.1 新增slot文本形式
 * v1.0.2 优化结构
 * v1.0.3 添加link属性
 * v2.0.0 升级交互
 * v2.1.0 使用border方式实现边框模块
 * v3.0.0 props从core导出
 */
import { defineComponent, h } from 'vue';
import { props } from '@shuimo-design/core/lib/base/button/api';


export default defineComponent({
  name: 'MButton',
  props,
  setup(props, { slots }) {
    return () => {

      const domType = props.link ? 'a' : 'button';
      const slot = slots.default?.() ?? props.text;
      return h(domType, {
        class: ['m-button', { 'm-button-disabled': props.disabled }, `m-button-${props.type}`],
        disabled: props.disabled
      },slot);

    };
  }
});
