// packages/lit/lib/base/MList.ts
/**
 * @description web-component version list
 * @author 阿怪
 * @date 2023/05/04 22:46
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * todo fix data type
 */
import { html, LitElement, unsafeCSS } from 'lit';
import { createMElement } from '../../base/createElement';
import { props } from '@shuimo-design/core/lib/base/list/api';
import { ListProps } from '@shuimo-design/core/lib/base/list';
import style from '@shuimo-design/core/lib/base/list/list.css?inline';
import { useList } from '@shuimo-design/core/lib/base/list/useList';

const { baseRender, dataValidate } = useList();
@createMElement({
  name: 'list',
  props: {
    ...props,
    data: { type: String, default: '' }
  }
})
export default class extends LitElement implements Omit<ListProps, 'data'> {
  autoActive: boolean = false;
  data: string = '';


  static styles = unsafeCSS(style);

  MLiRender(data: any, active: boolean) {
    return html`
      <m-li .active=${active}>${data}</m-li>`;
  }

  get parseData() {
    const _data = JSON.parse(this.data);
    if (!dataValidate(_data)) return [];
    return _data as any[];
  }

  render() {
    return html`
      <div class="m-list">
        ${this.parseData.map(d => this.MLiRender(baseRender(d), this.autoActive))}
      </div>`;
  }

}

// packages/vue/lib/base/MList.tsx
/**
 * @description list component
 * @author 阿怪
 * @date 2022/4/24 21:57
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 *
 * todo click toggle active and emit click event
 */
import { defineComponent, h } from 'vue';
import { props } from '@shuimo-design/core/lib/base/list/api';
import { useList } from '@shuimo-design/core/lib/base/list/useList';
import MLi from './MLi';


export default defineComponent({
  name: 'MList',
  props,
  setup: (props, { slots }) => {
    return () => {

      const { baseRender, dataValidate } = useList();

      if (!dataValidate(props.data)) {
        return;
      }

      const data = props.data;

      return <div class="m-list">
        {data.map(d => h(MLi, { active: d.active ?? props.autoActive }, {
          default: () => slots.default ? slots.default({ data: d }) : baseRender(d)
        }))}
      </div>;
    };
  }
});
