// packages/react/lib/template/MBorder.tsx
/**
 * @description react version border component
 * @author 阿怪
 * @date 2023/2/8 23:36
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */
import React, { HTMLAttributes } from 'react';
import '@shuimo-design/core/lib/template/border/border.css';
import { Slot } from '../../types';
import { baseLineClass, lineType } from '@shuimo-design/core/lib/template/border/lineType';

export default function MBorder(props: Slot & HTMLAttributes<HTMLDivElement>) {

  const lineTemplate = Object.keys(lineType).map(type => {
    return <div key={type} className={[baseLineClass, `m-border-${type}-line`].join(' ')}></div>;
  });
  return <div {...props} className={['m-border', props.className??''].join(' ')}>
    <div className="m-border-main">
      {props.children ?? null}
    </div>
    {lineTemplate}
  </div>;
}

// packages/vue/lib/template/border/MBorder.tsx
/**
 * @description 边框组件
 * @author 阿怪
 * @date 2021/8/23 8:45 下午
 * @version v2.0.0
 *
 * 公司的业务千篇一律，复杂的代码好几百行。
 * v2.0.0 阿怪 upgrade to core version
 */

import { defineComponent } from 'vue';
import { baseLineClass, lineType } from '@shuimo-design/core/lib/template/border/lineType';


export const MBorderOptions = (styleNode?, slot?) => {
  return {
    name: 'MBorder',
    setup(props, { slots }) {
      return () => {

        const lineTemplate = Object.keys(lineType).map(type => {
          return <div class={[baseLineClass, `m-border-${type}-line`]}></div>;
        });

        return <div class="m-border">
          {styleNode}
          <div class="m-border-main">
            {slot ?? slots.default?.()}
          </div>
          {lineTemplate}
        </div>;
      };
    }
  };
};

export default defineComponent(MBorderOptions());
